//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DankMemerConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DankMemerConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    /* This is a discord self bot script that was developed by rigwild
        ///     * All credit goes to rigwild for this script
        ///     * Source: https://github.com/rigwild/discord-self-bot-console
        ///     */
        ///    var delay = ms =&gt; new Promise(res =&gt; setTimeout(res, ms));
        ///    // prettier-ignore
        ///    var qs = obj =&gt; Object.entries(obj).map(([k, v]) =&gt; `${k}=${v}`).join(&quot;&amp;&quot;);
        ///
        ///    const apiCall = (apiPath, body, method = &quot;GET&quot;) =&gt; {
        ///        if (!authHeader)
        ///            throw new Error(
        ///                &quot;The aut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiscordSelfBotAPI {
            get {
                return ResourceManager.GetString("DiscordSelfBotAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function getElementsByXPath(xpath, parent) {
        ///    let results = [];
        ///    let query = document.evaluate(xpath, parent || document,
        ///        null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
        ///    for (let i = 0, length = query.snapshotLength; i &lt; length; ++i) {
        ///        results.push(query.snapshotItem(i));
        ///    }
        ///    return results;
        ///}.
        /// </summary>
        internal static string GetElementsByXPath {
            get {
                return ResourceManager.GetString("GetElementsByXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v3.6.0 -ajax,-ajax/jsonp,-ajax/load,-ajax/script,-ajax/var/location,-ajax/var/nonce,-ajax/var/rquery,-ajax/xhr,-manipulation/_evalUrl,-deprecated/ajax-event-alias,-effects,-effects/Tween,-effects/animatedSelector | (c) OpenJS Foundation and other contributors | jquery.org/license */
        ///!function(e,t){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=e.document?t(e,!0):function(e){if(!e.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return t(e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jquery {
            get {
                return ResourceManager.GetString("Jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function ShowSideBar() {
        ///    var results = getElementsByXPath(&apos;/html/body/div[1]/div[2]/div/div[2]/div/div/div/div/div[1]&apos;, document);
        ///    var sideBar = results[0];
        ///    sideBar.style.visibility = &apos;visible&apos;;
        ///    sideBar.style.width = &apos;240px&apos;;
        ///
        ///}
        ///
        ///function HideSideBar() {
        ///    var results = getElementsByXPath(&apos;/html/body/div[1]/div[2]/div/div[2]/div/div/div/div/div[1]&apos;, document);
        ///    var sideBar = results[0];
        ///    sideBar.style.visibility = &apos;collapse&apos;;
        ///    sideBar.style.width = &apos;0px&apos;;
        ///}.
        /// </summary>
        internal static string ToggleSideBar {
            get {
                return ResourceManager.GetString("ToggleSideBar", resourceCulture);
            }
        }
    }
}
